### ISSUE TITLE
License of seahash.c?

### ISSUE THREAD

**Issue by lindig** [warmwaffles/c-hashing#1]
Under what license is the code published in this directory? Specifically, I would be interested to use the implementation of seahash, which, unlike some of the others, does not have a copyright notice.

I have an unrelated question: does the code avoid reading beyond the buffer when it contains less than 8 bytes? It seems that all access is done via reading 8 bytes at a time. Or is there some requirement for the buffer to be a multiple of 8 bytes?

**Comment by warmwaffles** [comment]
@lindig I haven't honestly looked at this library in so long and haven't really had any interest since I pushed it to move forward.

Although I am coming around to this again, and I'll go through and re-update all of these with proper licenses and see if I can get some fuzz testing added.

**Comment by warmwaffles** [comment]
I'll also probably archive this repository and break it out into several sub repos so that only parts could be pulled into projects using `subtree`
